//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Web.Client.SFISEtlService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SFISEtlService.ETL_ServiceSoap")]
    public interface ETL_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServerTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime GetServerTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServerTime", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> GetServerTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Rv_Xml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SFIS_Rv_Xml(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Rv_Xml", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SFIS_Rv_XmlAsync(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ETL_Rv", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ETL_Rv(string sParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ETL_Rv", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ETL_RvAsync(string sParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Rv", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SFIS_Rv(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Rv", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SFIS_RvAsync(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Tx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SFIS_Tx(string sParam, string sType, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Tx", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SFIS_TxAsync(string sParam, string sType, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Rv_Factory_No", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SFIS_Rv_Factory_No(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Rv_Factory_No", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SFIS_Rv_Factory_NoAsync(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ETL_Tx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ETL_Tx(string sParam, string sType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ETL_Tx", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ETL_TxAsync(string sParam, string sType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ETL_ServiceSoapChannel : WMS.Web.Client.SFISEtlService.ETL_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ETL_ServiceSoapClient : System.ServiceModel.ClientBase<WMS.Web.Client.SFISEtlService.ETL_ServiceSoap>, WMS.Web.Client.SFISEtlService.ETL_ServiceSoap {
        
        public ETL_ServiceSoapClient() {
        }
        
        public ETL_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ETL_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ETL_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ETL_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime GetServerTime() {
            return base.Channel.GetServerTime();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetServerTimeAsync() {
            return base.Channel.GetServerTimeAsync();
        }
        
        public string SFIS_Rv_Xml(string sParam, string sWebServiceType) {
            return base.Channel.SFIS_Rv_Xml(sParam, sWebServiceType);
        }
        
        public System.Threading.Tasks.Task<string> SFIS_Rv_XmlAsync(string sParam, string sWebServiceType) {
            return base.Channel.SFIS_Rv_XmlAsync(sParam, sWebServiceType);
        }
        
        public System.Data.DataSet ETL_Rv(string sParam) {
            return base.Channel.ETL_Rv(sParam);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ETL_RvAsync(string sParam) {
            return base.Channel.ETL_RvAsync(sParam);
        }
        
        public System.Data.DataSet SFIS_Rv(string sParam, string sWebServiceType) {
            return base.Channel.SFIS_Rv(sParam, sWebServiceType);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SFIS_RvAsync(string sParam, string sWebServiceType) {
            return base.Channel.SFIS_RvAsync(sParam, sWebServiceType);
        }
        
        public string SFIS_Tx(string sParam, string sType, string sWebServiceType) {
            return base.Channel.SFIS_Tx(sParam, sType, sWebServiceType);
        }
        
        public System.Threading.Tasks.Task<string> SFIS_TxAsync(string sParam, string sType, string sWebServiceType) {
            return base.Channel.SFIS_TxAsync(sParam, sType, sWebServiceType);
        }
        
        public System.Data.DataSet SFIS_Rv_Factory_No(string sParam, string sWebServiceType) {
            return base.Channel.SFIS_Rv_Factory_No(sParam, sWebServiceType);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SFIS_Rv_Factory_NoAsync(string sParam, string sWebServiceType) {
            return base.Channel.SFIS_Rv_Factory_NoAsync(sParam, sWebServiceType);
        }
        
        public string ETL_Tx(string sParam, string sType) {
            return base.Channel.ETL_Tx(sParam, sType);
        }
        
        public System.Threading.Tasks.Task<string> ETL_TxAsync(string sParam, string sType) {
            return base.Channel.ETL_TxAsync(sParam, sType);
        }
    }
}
